import customInput from './custom-form-item/custom-input.vue'
import customSelect from './custom-form-item/custom-select.vue'
import customCheckbox from './custom-form-item/custom-checkbox.vue'
import customRadio from './custom-form-item/custom-radio.vue'
import customSwitch from './custom-form-item/custom-switch.vue'
import customSlider from './custom-form-item/custom-slider.vue'
import customRate from './custom-form-item/custom-rate.vue'
import customUpload from './custom-form-item/custom-upload.vue'
import customTreeSelect from './custom-form-item/custom-tree-select.vue'
import customCascader from './custom-form-item/custom-cascader.vue'
import customInputNumber from './custom-form-item/custom-input-number.vue'
import customDatePicker from './custom-form-item/custom-date-picker.vue'
import customRangePicker from './custom-form-item/custom-range-picker.vue'

export const compList = [
  {
    label: '输入框',
    componentName: 'Input',
    component: customInput,
    componentProps: [
      {
        name: 'placeholder',
        key: 'placeholder',
        type: 'string',
        options: [],
        default: '请输入内容',
        title: '默认提示',
      },
      {
        name: 'disabled',
        key: 'disabled',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否禁用',
      },
      {
        name: 'readonly',
        key: 'readonly',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否只读',
      },
      {
        name: 'required',
        key: 'required',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否必填',
      },
      {
        name: 'maxlength',
        key: 'maxlength',
        type: 'number',
        options: [],
        default: 32,
        title: '最大长度',
      },
    ],
    props: {
      placeholder: '请输入内容',
      disabled: false,
      readonly: false,
      allowClear: false,
      maxlength: 32,
      required: false,
    },
  },
  {
    label: '数字输入框',
    componentName: 'InputNumber',
    component: customInputNumber,
    componentProps: [
      {
        name: 'min',
        key: 'min',
        type: 'number',
        options: [],
        default: -Infinity,
        title: '数字输入框的最小值',
      },
      {
        name: 'max',
        key: 'max',
        type: 'number',
        options: [],
        default: Infinity,
        title: '数字输入框的最大值',
      },
      {
        name: 'step',
        key: 'step',
        type: 'number',
        options: [],
        default: 1,
        title: '数字输入框的步长',
      },
      {
        name: 'disabled',
        key: 'disabled',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否禁用',
      },
      {
        name: 'maxlength',
        key: 'maxlength',
        type: 'number',
        options: [],
        default: 32,
        title: '最大长度',
      },
    ],
    props: {
      min: 0,
      max: 100,
      step: 1,
      maxlength: 32,
      disabled: false,
    },
  },
  {
    label: '选择器',
    componentName: 'Select',
    component: customSelect,
    componentProps: [
      {
        name: 'placeholder',
        key: 'placeholder',
        type: 'string',
        options: [],
        default: '请选择',
        title: '默认提示',
      },
      {
        name: 'mode',
        key: 'mode',
        type: 'array',
        options: [
          { label: '单选', value: 'combobox' },
          { label: '多选', value: 'multiple' },
          { label: '标签', value: 'tags' },
        ],
        default: void 0,
        title: '选择框的模式',
      },
      {
        name: 'showSearch',
        key: 'showSearch',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否显示搜索框',
      },
      {
        name: 'required',
        key: 'required',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否必填',
      },
      {
        name: 'options',
        key: 'options',
        type: 'select',
        options: [],
        default: false,
        title: '选项设置',
      },
    ],
    props: {
      placeholder: '请选择',
      mode: 'combobox',
      allowClear: false,
      showSearch: false,
      required: false,
      options: [],
    },
  },
  {
    label: '多选择',
    componentName: 'Checkbox',
    component: customCheckbox,
    componentProps: [
      {
        name: 'disabled',
        key: 'disabled',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否禁用',
      },
      {
        name: 'options',
        key: 'options',
        type: 'select',
        options: [],
        default: false,
        title: '选项设置',
      },
    ],
    props: {
      disabled: false,
      options: [],
    },
  },
  {
    label: '单选框',
    componentName: 'Radio',
    component: customRadio,
    componentProps: [
      {
        name: 'disabled',
        key: 'disabled',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否禁用',
      },
      {
        name: 'options',
        key: 'options',
        type: 'select',
        options: [],
        default: false,
        title: '选项设置',
      },
    ],
    props: {
      disabled: false,
      options: [],
    },
  },
  {
    label: '开关',
    componentName: 'Switch',
    component: customSwitch,
    componentProps: [
      {
        name: 'disabled',
        key: 'disabled',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否禁用',
      },
      {
        name: 'loading',
        key: 'loading',
        type: 'boolean',
        options: [],
        default: false,
        title: '开关是否加载中',
      },
      {
        name: 'checkedChildren',
        key: 'checkedChildren',
        type: 'string',
        options: [],
        default: '开',
        title: '开关打开时的文本',
      },
      {
        name: 'unCheckedChildren',
        key: 'unCheckedChildren',
        type: 'string',
        options: [],
        default: '关',
        title: '开关关闭时的文本',
      },
    ],
    props: {
      disabled: false,
      loading: false,
      checkedChildren: '开',
      unCheckedChildren: '关',
    },
  },
  {
    label: '滑动输入条',
    componentName: 'Slider',
    component: customSlider,
    componentProps: [
      { name: 'min', key: 'min', type: 'number', options: [], default: 0, title: '滑块的最小值' },
      { name: 'max', key: 'max', type: 'number', options: [], default: 100, title: '滑块的最大值' },
      {
        name: 'range',
        key: 'range',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否为范围选择',
      },
      {
        name: 'disabled',
        key: 'disabled',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否禁用',
      },
    ],
    props: {
      min: 0,
      max: 100,
      range: false,
      disabled: false,
    },
  },
  {
    label: '评分',
    componentName: 'Rate',
    component: customRate,
    componentProps: [
      {
        name: 'count',
        key: 'count',
        type: 'number',
        options: [],
        default: 5,
        title: '评分的星星数量',
      },
      {
        name: 'allowHalf',
        key: 'allowHalf',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否允许半星',
      },
      {
        name: 'disabled',
        key: 'disabled',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否禁用',
      },
    ],
    props: {
      count: 5,
      allowHalf: false,
      disabled: false,
    },
  },
  {
    label: '上传',
    componentName: 'Upload',
    component: customUpload,
    componentProps: [
      {
        name: 'action',
        key: 'action',
        type: 'string',
        options: [],
        default: '',
        title: '上传的地址',
      },
      {
        name: 'multiple',
        key: 'multiple',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否支持多文件上传',
      },
      {
        name: 'directory',
        key: 'directory',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否支持文件夹上传',
      },
      {
        name: 'disabled',
        key: 'disabled',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否禁用',
      },
      {
        name: 'showUploadList',
        key: 'showUploadList',
        type: 'boolean',
        options: [],
        default: true,
        title: '是否显示上传列表',
      },
      {
        name: 'name',
        key: 'name',
        type: 'string',
        options: [],
        default: 'name',
        title: '上传的文件字段名',
      },
      {
        name: 'listType',
        key: 'listType',
        type: 'array',
        options: [
          { label: 'picture', value: 'picture' },
          { label: 'text', value: 'text' },
          { label: 'picture-card', value: 'picture-card' },
        ],
        default: 'picture-card',
        title: '上传列表的内建样式',
      },
    ],
    props: {
      action: '',
      multiple: false,
      directory: false,
      disabled: false,
      showUploadList: true,
      name: 'name',
      listType: 'picture-card',
    },
  },
  {
    label: '树型选择器',
    componentName: 'TreeSelect',
    component: customTreeSelect,
    componentProps: [
      {
        name: 'treeData',
        key: 'treeData',
        type: 'tree',
        options: [],
        default: [],
        title: '数据源',
      },
      {
        name: 'showSearch',
        key: 'showSearch',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否显示搜索框',
      },
      {
        name: 'allowClear',
        key: 'allowClear',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否允许清除选择内容',
      },
      {
        name: 'multiple',
        key: 'multiple',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否支持多选',
      },
    ],
    props: {
      treeData: [],
      showSearch: false,
      allowClear: false,
      multiple: false,
    },
  },
  {
    label: '级联选择器',
    componentName: 'Cascader',
    component: customCascader,
    componentProps: [
      {
        name: 'options',
        key: 'options',
        type: 'tree',
        options: [],
        default: [],
        title: '数据源',
      },
      {
        name: 'showSearch',
        key: 'showSearch',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否显示搜索框',
      },
      {
        name: 'allowClear',
        key: 'allowClear',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否允许清除选择内容',
      },
    ],
    props: {
      options: [],
      showSearch: false,
      allowClear: false,
      changeOnSelect: false,
    },
  },

  {
    label: '日期选择器',
    componentName: 'DatePicker',
    component: customDatePicker,
    componentProps: [
      {
        name: 'format',
        key: 'format',
        type: 'string',
        options: [],
        default: 'YYYY-MM-DD',
        title: '日期选择框的格式',
      },
      {
        name: 'disabled',
        key: 'disabled',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否禁用',
      },
      {
        name: 'showToday',
        key: 'showToday',
        type: 'boolean',
        options: [],
        default: true,
        title: '是否显示今天按钮',
      },
      {
        name: 'required',
        key: 'required',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否必填',
      },
    ],
    props: {
      format: 'YYYY-MM-DD',
      showTime: false,
      disabled: false,
      showToday: true,
      required: false,
    },
  },
  {
    label: '范围选择器',
    componentName: 'RangePicker',
    component: customRangePicker,
    componentProps: [
      {
        name: 'format',
        key: 'format',
        type: 'string',
        options: [],
        default: 'YYYY-MM-DD',
        title: '日期范围选择框的格式',
      },
      {
        name: 'showTime',
        key: 'showTime',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否显示时间选择',
      },
      {
        name: 'disabled',
        key: 'disabled',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否禁用',
      },
      {
        name: 'required',
        key: 'required',
        type: 'boolean',
        options: [],
        default: false,
        title: '是否必填',
      },
    ],
    props: {
      format: 'YYYY-MM-DD',
      showTime: false,
      disabled: false,
      required: false,
    },
  },
]
